all: genClau genOut

genClau:		genClau.cpp
		g++ -O3 -Wall -std=c++11 -o genClau genClau.cpp

genOut: 		genOut.cpp
		g++ -O3 -Wall -std=c++11 -o genOut genOut.cpp

clean:
		rm -f  genClau core *~  genOut core *~ 